export const productList = [
  {
    id: 1,
    name: "Product 1",
    price: 10.99,
    description: "This is the description for Product 1.",
    image: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Product 2",
    price: 19.99,
    description: "This is the description for Product 2.",
    image: "https://via.placeholder.com/150",
  },                
    {id: 3,
    name: "Product 3",
    price: 5.99,
    description: "This is the description for Product 3.",
    image: "https://via.placeholder.com/150",
  },
   {id: 4,
    name: "Product 4",
    price: 15.99,
    description: "This is the description for Product 4.",
    image: "https://via.placeholder.com/150",
  },
   {id: 5,
    name: "Product 5",
    price: 8.99,
    description: "This is the description for Product 5.",
    image: "https://via.placeholder.com/150",
  },        
];